# Generated by Django 4.1.3 on 2022-11-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='fech_publicacion',
            field=models.DateField(default='2000-06-22'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
