# Generated by Django 4.1.3 on 2022-11-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_libros_fech_publicacion_alter_libros_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante_oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=100)),
                ('perfil', models.IntegerField(choices=[('FrontEnd', 'Horror'), ('BackEnd', 'Comedy')], default=0)),
                ('nivel', models.CharField(choices=[('Junior', 'Junior'), ('Semisenior', 'Semisenior'), ('Senior', 'Senior')], max_length=100)),
                ('fech_nacimiento', models.DateField(default='2000-06-22')),
            ],
        ),
        migrations.DeleteModel(
            name='Libros',
        ),
    ]
