# Generated by Django 4.1.3 on 2022-11-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_postulante_oferta_delete_libros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante_oferta',
            name='perfil',
            field=models.CharField(choices=[('FrontEnd', 'Horror'), ('BackEnd', 'Comedy')], max_length=100),
        ),
    ]
